### ISSUE TITLE
Documentation on how to use

### ISSUE THREAD

**Issue by chulkilee** [whatyouhide/code_formatter#15]
First of all, thanks a lot for this tool - I really miss this kind of tool (I'm a fan of gofmt or rubocop).

I know it's still early stage, but for anyone who wants to try this tool: here is how I use this

1. Clone `code_formatter` somewhere
1. Install [asdf](https://github.com/asdf-vm/asdf)
1. Install Elixir master version with `asdf` and configure to use it
1. Use the following helper script to check against files

```sh
#!/usr/local/bin/bash -eu
# system bash on Mac is too old

shopt -s globstar
shopt -s nullglob

root=$1

mix run script.exs --verbose --save "$1"/{config,lib,test}/**/*.{ex,exs} # "$1"/mix.exs
```

I hope in the future I can just include a package into my project, and run mix tasks to use it (like [credo](https://hex.pm/packages/credo)) .. or install it as standalone executable (like [rubocop](https://github.com/bbatsov/rubocop))

**Comment by josevalim** [comment]
Thanks for documenting it. It is hard now on purpose, since it is not really ready. And it will be included in Elixir v1.6 under the `mix format` task. :)

**Comment by whatyouhide** [comment]
I think we can close this issue now that the code formatter has been merged into Elixir and https://github.com/elixir-lang/elixir/pull/6642 is about to introduce the Mix task. :)

**Comment by chulkilee** [comment]
Yeah! Then could you update description of this repo (or README) to mention that all work should be done on Elixir, not this repo? :)
